# codiff completions for fish. Generated by `codiff --completions fish`.

function __codiff_refs
    command git for-each-ref --format='%(refname:short)' refs/heads refs/remotes refs/tags 2>/dev/null
end

# The ref is only completable while it is still the argument being typed: once it
# is given, as a word or through a flag, the repository path is all that is left.
function __codiff_expects_ref
    set -l tokens (commandline --current-process --tokens-expanded --cut-at-cursor)
    set -e tokens[1]
    set -l skip 0
    for token in $tokens
        if test $skip -eq 1
            set skip 0
            continue
        end
        switch $token
            case --branch '--branch=*' --commit '--commit=*' --plan '--plan=*'
                return 1
            case --agent --branch --claude-session --commit --codex-session --completions --opencode-session --pi-session --plan --walkthrough-context --walkthrough-file
                set skip 1
            case '-*'
            case '*'
                return 1
        end
    end
    return 0
end

complete -c codiff -n __codiff_expects_ref -a '(__codiff_refs)' -d 'Git ref'
complete -c codiff -l agent -x -a 'claude codex opencode pi' -d 'Override the agent backend for this session.'
complete -c codiff -l branch -x -a '(__codiff_refs)' -d 'Review the current branch against a target branch.'
complete -c codiff -l claude-session -x -d 'Attach Claude Code session metadata to a walkthrough.'
complete -c codiff -l commit -x -a '(__codiff_refs)' -d 'Review a specific commit.'
complete -c codiff -l codex-session -x -d 'Attach Codex session metadata to a walkthrough.'
complete -c codiff -l completions -x -a 'bash fish zsh' -d 'Print a shell completion script, then exit.'
complete -c codiff -s h -l help -d 'Show this help message and exit.'
complete -c codiff -l opencode-session -x -d 'Attach OpenCode session metadata to a walkthrough.'
complete -c codiff -l pi-session -x -d 'Attach Pi session metadata to a walkthrough.'
complete -c codiff -l plan -r -F -d 'Edit a Markdown plan and wait until it is handed back.'
complete -c codiff -l share -d 'Share a walkthrough or a --plan file, then print its URL.'
complete -c codiff -s v -l version -d 'Show version number and exit.'
complete -c codiff -s w -l walkthrough -d 'Start an LLM walkthrough; use HEAD when there are no local changes.'
complete -c codiff -l walkthrough-context -r -F -d 'Seed a walkthrough with Codex conversation context JSON.'
complete -c codiff -l walkthrough-file -r -F -d 'Open a pre-authored narrative walkthrough JSON file.'
complete -c codiff -l walkthrough-guide -d 'Print the narrative walkthrough authoring guide and schema, then exit.'
